In [2]:
import time
import numpy as np 
# import matplotlib.pyplot as plt  
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import learning_curve
from sklearn.kernel_ridge import KernelRidge

#set input data file
url = "realData4D.csv"

# Assign colum names to the dataset
colnames = ['x1', 'x2', 'x2', 'x3', 'Val']

# Read dataset
X = np.loadtxt(url, dtype=float,delimiter=';',skiprows=1, usecols=(0,1,2,3))
y = np.loadtxt(url, dtype=float,delimiter=';',skiprows=1, usecols=4)

#split training data and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=0)

kr = GridSearchCV(KernelRidge(kernel='rbf', gamma=0.1), cv=5,param_grid={"degree":[3,4,5,6],"alpha": [1e0, 0.1, 1e-2, 1e-3],"gamma": np.logspace(-2, 2, 5)})

kr_poly = GridSearchCV(KernelRidge(kernel='poly', gamma=0.1), cv=5,param_grid={"degree":[4,5,6],"alpha": [1e0, 0.1, 1e-2, 1e-3],"gamma": np.logspace(-2, 2, 5)})

svr_rbf = GridSearchCV(SVR(kernel='rbf', C=0.7), cv=5,param_grid={"C": [0.5, 0.6, 0.7],"gamma": np.logspace(-2, 2, 5)})

svr_poly = SVR(kernel='poly', C=0.7, degree=4)


t0 = time.time()
svr_rbf.fit(X_train, y_train)
svr_rbf_fit = time.time() - t0
print("SVR rbf complexity and bandwidth selected and model fitted in %.3f s"
      % svr_rbf_fit)
print("SVR rbf score: %.3f" %svr_rbf.score(X_test, y_test))

t0 = time.time()
svr_poly.fit(X_train, y_train)
svr_poly_fit = time.time() - t0
print("SVR poly complexity and bandwidth selected and model fitted in %.3f s"
      % svr_poly_fit)
print("SVR poly score: %.3f" %svr_poly.score(X_test, y_test))

t0 = time.time()
kr.fit(X_train, y_train)
kr_fit = time.time() - t0
print("KRR complexity and bandwidth selected and model fitted in %.3f s"
      % kr_fit)
print("KR score: %.3f" %kr.score(X_test, y_test))

t0 = time.time()
kr_poly.fit(X_train, y_train)
kr_poly_fit = time.time() - t0
print("KRR complexity and bandwidth selected and model fitted in %.3f s"
      % kr_poly_fit)
print("KR poly score: %.3f" %kr_poly.score(X_test, y_test))

sv_rbf_ratio = svr_rbf.best_estimator_.support_.shape[0] / 90
print("Support vector with rbf kernel ratio: %.3f" % sv_rbf_ratio)

#sv_poly_ratio = svr_poly.best_estimator_.support_.shape[0] / train_size
#print("Support vector with polynomial kernel ratio: %.3f" % sv_poly_ratio)

t0 = time.time()
y_svr_rbf = svr_rbf.predict(X_test)
svr_rbf_predict = time.time() - t0
print("SVR rbf prediction for %d inputs in %.3f s"
      % (X_test.shape[0], svr_rbf_predict))

#t0 = time.time()
#y_svr_poly = svr_poly.predict(X_test)
#svr_poly_predict = time.time() - t0
#print("SVR rbf prediction for %d inputs in %.3f s"
#      % (X_test.shape[0], svr_poly_predict))

t0 = time.time()
y_kr = kr.predict(X_test)
kr_predict = time.time() - t0
print("KRR prediction for %d inputs in %.3f s"
      % (X_test.shape[0], kr_predict))

print("Kernel Ridges ptimization using gridsearchCV result:")
print(kr.cv_results_)


print("RBF optimization using gridsearchCV result:")
print(svr_rbf.cv_results_)

SVR rbf complexity and bandwidth selected and model fitted in 0.117 s
SVR rbf score: 0.073
SVR poly complexity and bandwidth selected and model fitted in 0.000 s
SVR poly score: 0.006
KRR complexity and bandwidth selected and model fitted in 2.200 s
KR score: 0.867


/home/iqbal/anaconda3/lib/python3.6/site-packages/scipy/linalg/basic.py:223: RuntimeWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number: 1.0816080641028584e-17
  ' condition number: {}'.format(rcond), RuntimeWarning)
/home/iqbal/anaconda3/lib/python3.6/site-packages/scipy/linalg/basic.py:223: RuntimeWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number: 6.845746240481367e-18
  ' condition number: {}'.format(rcond), RuntimeWarning)
/home/iqbal/anaconda3/lib/python3.6/site-packages/scipy/linalg/basic.py:223: RuntimeWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number: 1.007163250974947e-17
  ' condition number: {}'.format(rcond), RuntimeWarning)
/home/iqbal/anaconda3/lib/python3.6/site-packages/scipy/linalg/basic.py:223: RuntimeWarning: scipy.linalg.solve
Ill-c

KRR complexity and bandwidth selected and model fitted in 0.860 s
KR poly score: 0.882
Support vector with rbf kernel ratio: 0.056
SVR rbf prediction for 10 inputs in 0.000 s
KRR prediction for 10 inputs in 0.001 s
Kernel Ridges ptimization using gridsearchCV result:
{'mean_fit_time': array([ 0.25691805,  0.00077348,  0.00076828,  0.00078502,  0.00080533,
        0.00076389,  0.0007618 ,  0.00079155,  0.00078487,  0.00078821,
        0.00076818,  0.00076828,  0.0007668 ,  0.00078626,  0.00079231,
        0.00076828,  0.00076456,  0.00077977,  0.0007812 ,  0.00079427,
        0.00076609,  0.00076957,  0.00077   ,  0.00077753,  0.00079994,
        0.00076275,  0.00076971,  0.00077372,  0.00076218,  0.00080404,
        0.00075884,  0.00075512,  0.00076709,  0.00077314,  0.00079207,
        0.00076375,  0.00076694,  0.00075641,  0.00076318,  0.00080047,
        0.00075645,  0.00076308,  0.00083947,  0.00076723,  0.00080452,
        0.00076299,  0.00075793,  0.00077348,  0.00077586,  0.0007

/home/iqbal/anaconda3/lib/python3.6/site-packages/scipy/linalg/basic.py:223: RuntimeWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number: 2.02676273421236e-20
  ' condition number: {}'.format(rcond), RuntimeWarning)
/home/iqbal/anaconda3/lib/python3.6/site-packages/scipy/linalg/basic.py:223: RuntimeWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number: 2.4246852054662888e-20
  ' condition number: {}'.format(rcond), RuntimeWarning)
/home/iqbal/anaconda3/lib/python3.6/site-packages/scipy/linalg/basic.py:223: RuntimeWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number: 3.863348234811818e-20
  ' condition number: {}'.format(rcond), RuntimeWarning)
/home/iqbal/anaconda3/lib/python3.6/site-packages/scipy/linalg/basic.py:223: RuntimeWarning: scipy.linalg.solve
Ill-co

In [3]:
x1 =np.arange(0,1,0.0001)
x2 =np.arange(0,1,0.0001)
x3 =np.arange(0,1,0.0001)
x4 =np.arange(0,1,0.0001)
X_predict_permil = np.array([x1,x2,x3,x4]).T
y_predict_permil = kr.predict(X_predict_permil)
print(X_predict_permil)
print(y_predict_permil)
print(np.amin(y))
print(np.amin(y_predict_permil))

[[  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.00000000e-04   1.00000000e-04   1.00000000e-04   1.00000000e-04]
 [  2.00000000e-04   2.00000000e-04   2.00000000e-04   2.00000000e-04]
 ..., 
 [  9.99700000e-01   9.99700000e-01   9.99700000e-01   9.99700000e-01]
 [  9.99800000e-01   9.99800000e-01   9.99800000e-01   9.99800000e-01]
 [  9.99900000e-01   9.99900000e-01   9.99900000e-01   9.99900000e-01]]
[ 0.9334926   0.9333905   0.93328833 ...,  0.9181669   0.9181847
  0.91820248]
0.542638110396
0.721852564382


In [19]:
from sklearn.model_selection import StratifiedKFold
from genetic_selection import GeneticSelectionCV
import pandas as pd

paramgrid = {"kernel": ["rbf"],
             "C"     : np.logspace(-9, 9, num=25, base=10),
             "gamma" : np.logspace(-9, 9, num=25, base=10)}

paramgrid_krr = {"degree":[3,4,5,6],
                 "alpha": [1e0, 0.1, 1e-2, 1e-3],
                 "gamma": np.logspace(-2, 2, 5)}

#svr_ea = EvolutionaryAlgorithmSearchCV(estimator=SVR(),
#                                   params=paramgrid,
#                                   scoring="accuracy",
#                                   cv=StratifiedKFold(n_splits=4),
#                                   verbose=1,
#                                   population_size=90,
#                                   gene_mutation_prob=0.10,
#                                   gene_crossover_prob=0.5,
#                                   tournament_size=3,
#                                   generations_number=5,
#                                   n_jobs=4)
krr_ea = EvolutionaryAlgorithmSearchCV(estimator=KernelRidge(kernel='rbf', gamma=0.1),
                                   params=paramgrid_krr,
                                   scoring="accuracy",
                                   #cv=StratifiedKFold(n_splits=4),
                                   cv=5,
                                   verbose=1,
                                   population_size=90,
                                   gene_mutation_prob=0.10,
                                   gene_crossover_prob=0.5,
                                   tournament_size=3,
                                   generations_number=5,
                                   n_jobs=4)
test = np.array([np.arange(0,89,1),np.arange(0,89,1)]).T
print(X_train.shape)
print(y_train.shape)
krr_ea.fit(test, y_train)
print("done!")

(89, 4)
(89,)
Types [1, 2, 2] and maxint [3, 3, 4] detected


/home/iqbal/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMax' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/home/iqbal/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)


--- Evolve in 80 possible combinations ---


ValueError: continuous is not supported